name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-action@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test --release

      - name: Build runtime library
        run: cargo build --release -p perry-runtime

      - name: Test TypeScript compilation
        run: |
          # Create a simple test file
          echo 'console.log("Hello from Perry!");' > /tmp/test_hello.ts
          cargo run --release -- /tmp/test_hello.ts -o /tmp/test_hello
          /tmp/test_hello

  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-action@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ubuntu-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release

      - name: Build runtime library
        run: cargo build --release -p perry-runtime

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: perry-linux-x86_64
          path: |
            target/release/perry
            target/release/libperry_runtime.a

  build-macos:
    name: Build macOS Binary
    runs-on: macos-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-action@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: macos-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release

      - name: Build runtime library
        run: cargo build --release -p perry-runtime

      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: perry-macos-x86_64
          path: |
            target/release/perry
            target/release/libperry_runtime.a
