name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: perry-linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: perry-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: perry-macos-aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-action@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build runtime library
        run: cargo build --release -p perry-runtime --target ${{ matrix.target }}

      - name: Create archive
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/perry dist/
          cp target/${{ matrix.target }}/release/libperry_runtime.a dist/
          cd dist && tar -czvf ../${{ matrix.artifact_name }}.tar.gz *

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.tar.gz

  create-release:
    name: Create GitHub Release
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.tar.gz
          generate_release_notes: true
